import { useRef, useState } from 'react';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Navigation } from 'swiper';

import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import { fetchContent, HomepageConfig, ProductConfig, RelatedProductsConfig, strapiImage } from '../../../api';

import DefaultLayout from '../../../layouts/DefaultLayout';

import Fire from '../../../images/icons/fire.svg';
import InputArrowLeft from '../../../images/icons/input-arrow-left.svg';
import InputArrowRight from '../../../images/icons/input-arrow-right.svg';


export default function Product({ data }) {
  // swiper arrows
  const prevArrowRef = useRef();
  const nextArrowRef = useRef();

  // image gallery
  const [displayedImageId, setDisplayedImageId] = useState(0);

  const handleImageChange = (imageIndex) => {
    setDisplayedImageId(imageIndex);
  }

  return (
    <>
      <Head>
        <title>{data.Information.Model}, {data.Information.Title} – Газовий водонагрівач</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DefaultLayout>
        <section className="breadcrumbs">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <ul className="nav">
                  <li className="nav-item">
                    <Link href="/">
                      <a className="nav-link">
                        Головна
                      </a>
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/catalog">
                      <a className="nav-link">
                        Каталог
                      </a>
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/catalog">
                      <a className="nav-link">
                        {data.Category}
                      </a>
                    </Link>
                  </li>
                  <li className="nav-item">
                    <Link href="/catalog/photo-panel/branch">
                      <a className="nav-link">
                        {data.Information.Model}, <span>{data.Information.Title}</span>
                      </a>
                    </Link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </section>
        <section className="product">
          <div className="container">
            <div className="row justify-content-between">
              <div className="col-9">
                <div className="row gx-5">
                  <div className="col-auto">
                    <div className="product-gallery">
                      <div className="gallery-thumbnails">
                        {
                          data.Information.ImageGallery.data.map((image, index) => (
                            <div
                              className={`thumbnail-block image-${index} ${displayedImageId === index && 'active'}`}
                              key={index}
                              onClick={() => handleImageChange(index)}
                            >
                              <Image src={strapiImage(image.attributes.url)} width="80" height="110" alt="Waterheater Index"/>
                            </div>
                          ))
                        }
                      </div>
                      <div className="gallery-image">
                        <Image src={strapiImage(data.Information.ImageGallery.data[displayedImageId].attributes.url)} width="240" height="400" alt="Waterheater Index"/>
                      </div>
                    </div>
                  </div>
                  <div className="col-6">
                    <div className="product-content">
                      <div className="row">
                        <div className="col-12">
                          <div className="product-title">
                            {data.Information.Model}, <span>{data.Information.Title}</span>
                          </div>
                        </div>
                        <div className="col-12">
                          <div className="row gx-3">
                            <div className="col-auto">
                              <div className="product-headline">
                                {data.Information.Volume}
                              </div>
                            </div>
                            <div className="col-auto">
                              <div className="product-headline">
                                {data.Information.Type}
                              </div>
                            </div>
                          </div>
                        </div>
                        <div className="col-12">
                          <div className="product-description">
                            <p>
                              {data.Information.Description}
                            </p>
                          </div>
                          <div className="product-variations">
                            <div className="variations-title">
                              Інші товари з цієї категорії
                            </div>
                            <div className="d-flex align-items-center">
                              <Swiper
                                modules={[Navigation]}
                                spaceBetween={15}
                                slidesPerView={3}
                                speed={800}
                                className="variations-slider"
                                navigation={{
                                  prevEl: '.swiper-button-prev',
                                  nextEl: '.swiper-button-next'
                                }}
                                onInit={(swiper) => {
                                  swiper.params.navigation.prevEl = prevArrowRef.current;
                                  swiper.params.navigation.nextEl = nextArrowRef.current;
                                  swiper.navigation.init();
                                  swiper.navigation.update();
                                }}
                              >
                                {
                                  data.Information.RelatedProducts.data.map((product, productIndex) => (
                                    <SwiperSlide key={productIndex}>
                                      <Link href={`/catalog/product/${product.id}`}>
                                        <div className="variation-block">
                                          <Image src={strapiImage(product.attributes.FeaturedImage.data.attributes.url)} width="80" height="110" alt="Waterheater Index"/>
                                        </div>
                                      </Link>
                                    </SwiperSlide>
                                  ))
                                }
                              </Swiper>
                              <div className="variations-slider-arrows">
                                <div className="arrow-button" ref={prevArrowRef}>
                                  <Image src={InputArrowLeft} alt="Arrow Left Icon"/>
                                </div>
                                <div className="arrow-button" ref={nextArrowRef}>
                                  <Image src={InputArrowRight} alt="Arrow Right Icon"/>
                                </div>
                              </div>
                            </div>
                          </div>
                          <div className="product-price">
                            <div className="price-label">
                              Вартість:
                            </div>
                            <div className="price-number">
                              {data.Information.Price} грн
                            </div>
                          </div>
                          <div className="product-specifications">
                            <div className="title-with-icon">
                              <div className="icon">
                                <Image src={Fire} alt="Fire Icon"/>
                              </div>
                              <h4 className="title">
                                Характеристики
                              </h4>
                            </div>
                            <table className="specifications-table">
                              <tbody>
                              {
                                data.Specifications.Table.map((row, index) => (
                                  <tr key={index}>
                                    <th>
                                      <span>
                                        {row.Title}
                                      </span>
                                    </th>
                                    <td>
                                      {row.Value}
                                    </td>
                                  </tr>
                                ))
                              }
                              </tbody>
                            </table>
                          </div>
                          <div className="product-benefits">
                            <div className="title-with-icon">
                              <div className="icon">
                                <Image src={Fire} alt="Fire Icon"/>
                              </div>
                              <h4 className="title">
                                Безпека
                              </h4>
                            </div>
                            <table className="specifications-table">
                              <tbody>
                              {
                                data.Safety.Table.map((row, index) => (
                                  <tr key={index}>
                                    <th>
                                      {
                                        index === 0 && (
                                          <span>
                                            {row.Title}
                                          </span>
                                        )
                                      }
                                    </th>
                                    <td>
                                      {row.Value}
                                    </td>
                                  </tr>
                                ))
                              }
                              </tbody>
                            </table>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-3">
                <div className="frame-block product-order">
                  <div className="order-title">
                    Оформити замовлення
                  </div>
                  <form action="#">
                    <div className="row gy-4">
                      <div className="col-12">
                        <label htmlFor="name" className="form-label required">
                          Повне ім’я (ПІБ)
                        </label>
                        <input type="text" className="form-control" name="name" placeholder="Олександр" required/>
                      </div>
                      <div className="col-12">
                        <label htmlFor="phone" className="form-label required">
                          Контактний телефон
                        </label>
                        <input type="text" className="form-control" name="phone" placeholder="+38 (000) 00 00 000"
                               required/>
                      </div>
                      <div className="col-12">
                        <label htmlFor="question" className="form-label required">
                          Адреса доставки (Нова Пошта)
                        </label>
                        <select name="delivery-address" className="form-select">
                          <option value="Оберіть відділення" selected>Оберіть відділення</option>
                          <option value="Відділення 2">Відділення 1</option>
                          <option value="Відділення 2">Відділення 2</option>
                          <option value="Відділення 2">Відділення 3</option>
                        </select>
                      </div>
                      <div className="col-12 pt-3 pb-3">
                        <div className="row align-items-center gx-5">
                          <div className="col-auto">
                            <div className="order-price">
                              <div className="price-label">
                                Вартість:
                              </div>
                              <div className="price-number">
                                4000 грн
                              </div>
                            </div>
                          </div>
                          <div className="col-auto">
                            <div className="input-with-arrows">
                              <div className="arrow-button">
                                <Image src={InputArrowLeft} alt="Input Arrow Left"/>
                              </div>
                              <input type="text" className="form-control" min="1" step="1" max="10" defaultValue="1"
                                     readOnly/>
                              <div className="arrow-button">
                                <Image src={InputArrowRight} alt="Input Arrow Right"/>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="col-12">
                        <button className="btn btn-primary" type="submit">
                          Підтвердити замовлення
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
        {
          1 === 0 && (
            <>
              <section className="loading">
                <div className="container">
                  <div className="row justify-content-center align-items-center">
                    <div className="col-auto">
                      <div className="spinner-border text-primary" role="status">
                        <span className="visually-hidden">Завантаження...</span>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
              <section className="error">
                <div className="container">
                  <div className="row justify-content-center align-items-center">
                    <div className="col-auto">
                      <div className="error-block">
                        <div className="block-icon">
                          icon
                        </div>
                        <div className="block-content">
                          <div className="block-title">
                            Отакої.. Виникла помилка!
                          </div>
                          <div className="block-description">
                            Роботу сторінки буде відновлено незабаром.<br />
                            А поки – перегляньте інші товари або ж дізнйтесь про нас більше.
                          </div>
                          <div className="block-actions">
                            <button className="btn btn-primary">
                              Повернутись на головну
                            </button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </section>
            </>
          )
        }
      </DefaultLayout>
    </>
  );
}

export const getServerSideProps = async ({ res, params }) => {
  try {
    const data = await fetchContent(`products/${params.id}`, ProductConfig);

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: {},
  };
};