import Head from 'next/head';
import Link from 'next/link';
import Image from 'next/image';

import DefaultLayout from '../../layouts/DefaultLayout';

import WaterheaterBranch from '../../images/waterheaters/branch.png';
import { CatalogConfig, fetchContent, HomepageConfig, strapiImage } from '../../api';
import { Swiper, SwiperSlide } from 'swiper/react';

export default function Catalog({ data }) {

  console.log(data);

  return (
    <>
      <Head>
        <title>DION – Каталог</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DefaultLayout>
        <section className="hero-banner">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-8 text-center">
                <h1 dangerouslySetInnerHTML={{__html: data.HeroBanner.Title}} />
                <p dangerouslySetInnerHTML={{__html: data.HeroBanner.Description}} />
                <button className="btn btn-primary">
                  {data.HeroBanner.ButtonTitle}
                </button>
              </div>
            </div>
          </div>
        </section>
        {
          data.Category.map((category, categoryIndex) => (
            <section className="products-category" key={categoryIndex}>
              <div className="container">
                <div className="row">
                  <div className="col-12 pb-4">
                    <div className="title-with-icon">
                      <div className="icon">
                        <Image src={strapiImage(category.Icon.data.attributes.url)} width={18} height={18} alt="Fire Icon"/>
                      </div>
                      <h4 className="title">
                        {category.Title}
                      </h4>
                    </div>
                  </div>
                  <div className="col-12">
                    <Swiper
                      spaceBetween={24}
                      slidesPerView={5}
                      speed={800}
                      className="products-slider"
                    >
                      {
                        category.Products.data.map((product, productIndex) => (
                          <SwiperSlide key={productIndex}>
                            <div className="product-block">
                              <div className="block-image">
                                <Link href={`/catalog/product/${product.id}`}>
                                  <a>
                                    <Image src={strapiImage(product.attributes.FeaturedImage.data.attributes.url)} width={180} height={300} alt="Waterheater Index" />
                                  </a>
                                </Link>
                              </div>
                              <div className="block-content">
                                <div className="block-title">
                                  <Link href={`/catalog/product/${product.id}`}>
                                    <a>
                                      {product.attributes.Model}, <span>{product.attributes.Title}</span>
                                    </a>
                                  </Link>
                                </div>
                                <div className="block-price">
                                  {product.attributes.Price} грн
                                </div>
                              </div>
                            </div>
                          </SwiperSlide>
                        ))
                      }
                    </Swiper>
                  </div>
                </div>
              </div>
            </section>
          ))
        }
      </DefaultLayout>
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const data = await fetchContent('catalog', CatalogConfig);

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: {},
  };
};