import React from 'react';
import Head from 'next/head';
import DefaultLayout from '../layouts/DefaultLayout';

export default function Business() {
  return (
    <>
      <Head>
        <title>DION – Для бізнесу</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DefaultLayout>
        <section className="hero-banner">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-8 text-center">
                <h1>
                  Ми відкриті до різного<br />
                  виду партнерства.
                </h1>
                <p>
                  Оптова торгівля разом з Dion — це просто.
                  Також відкриті до комісійного виду співпраці.
                </p>
                <button className="btn btn-primary">
                  Стати партнером
                </button>
              </div>
            </div>
          </div>
        </section>
      </DefaultLayout>
    </>
  );
}