import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';

import DefaultLayout from '../layouts/DefaultLayout';

import Map from '../images/placeholders/map.jpg';
import { ContactsConfig, fetchContent, strapiImage } from '../api';

export default function Contacts({ data }) {
  console.log(data);

  return (
    <>
      <Head>
        <title>DION – Контакти</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DefaultLayout>
        <section className="contacts">
          <div className="container">
            <div className="row gx-xl-5 gy-5">
              <div className="col-12 col-xl-8">
                <div className="frame-block h-100">
                  <div className="row h-100 gy-5">
                    <div className="col-12 col-xl-6">
                      <h3>
                        {data.ContactsSection.Title}
                      </h3>
                      <div className="row gy-4">
                        {
                          data.ContactsSection.Contacts.map((contact, contactIndex) => (
                            <div className="col-12" key={contactIndex}>
                              <div className="contact-block">
                                <div className="block-title">
                                  {contact.Label}
                                </div>
                                <div className="block-content">
                                  <div className="block-icon">
                                    <Image src={strapiImage(contact.Icon.data.attributes.url)} layout="fixed" width={18} height={18} alt="Fire Icon" />
                                  </div>
                                  <div className="block-description">
                                    <Link href="#">
                                      {contact.Value}
                                    </Link>
                                  </div>
                                </div>
                              </div>
                            </div>
                          ))
                        }
                      </div>
                    </div>
                    <div className="col-12 col-xl-6 h-100">
                      <div className="map-block">
                        <Image src={Map} alt="Map Image"/>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-12 col-xl-4">
                <div className="frame-block">
                  <h3>
                    {data.Form.Title}
                  </h3>
                  <p dangerouslySetInnerHTML={{__html: data.Form.Description}} />
                  <form action="#">
                    <div className="row gy-4">
                      <div className="col-12">
                        <label htmlFor="name" className="form-label required">
                          Ім’я
                        </label>
                        <input type="text" className="form-control" name="name" placeholder="Олександр" required />
                      </div>
                      <div className="col-12">
                        <label htmlFor="phone" className="form-label required">
                          Контактний телефон
                        </label>
                        <input type="text" className="form-control" name="phone" placeholder="+38 (000) 00 00 000" required />
                      </div>
                      <div className="col-12">
                        <label htmlFor="question" className="form-label">
                          Ваше запитання
                        </label>
                        <textarea className="form-control" name="question" placeholder="Опишіть коротко вашу проблему" />
                      </div>
                      <div className="col-12">
                        <button className="btn btn-primary" type="submit">
                          Зворотній виклик
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
      </DefaultLayout>
    </>
  );
}

export const getStaticProps = async () => {
  try {
    const data = await fetchContent('contact', ContactsConfig);

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: {},
  };
};