import Link from 'next/link';
import { Swiper, SwiperSlide } from 'swiper/react';

import Head from 'next/head';
import Image from 'next/image';
import DefaultLayout from '../layouts/DefaultLayout';

import Map from '../images/placeholders/map.jpg';
import { fetchContent, HomepageConfig, strapiImage } from '../api';

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>DION – Газові водонагрівачі</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <DefaultLayout>
        <section className="hero-banner">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-12 col-xl-8 text-center">
                <h1 dangerouslySetInnerHTML={{__html: data.HeroBanner.Title}} />
                <p dangerouslySetInnerHTML={{__html: data.HeroBanner.Description}} />
                <Link href="/catalog">
                  <button className="btn btn-primary">
                    {data.HeroBanner.ButtonTitle}
                  </button>
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="popular-products">
          <div className="container">
            <div className="row">
              <div className="col-12 pb-4">
                <div className="title-with-icon">
                  <div className="icon">
                    <Image src={strapiImage(data.PopularProducts.Icon.data.attributes.url)} width={18} height={18} alt="Fire Icon" />
                  </div>
                  <h4 className="title">
                    {data.PopularProducts.Title}
                  </h4>
                </div>
              </div>
              <div className="col-12">
                <Swiper
                  spaceBetween={24}
                  slidesPerView={1.5}
                  speed={800}
                  breakpoints={{
                    768: {
                      slidesPerView: 5,
                    },
                  }}
                  className="products-slider"
                >
                  {
                    data.PopularProducts.Products.data.map((product, productIndex) => (
                      <SwiperSlide key={productIndex}>
                        <div className="product-block">
                          <div className="block-image">
                            <Link href={`/catalog/product/${product.id}`}>
                              <a>
                                <Image src={strapiImage(product.attributes.FeaturedImage.data.attributes.url)} width={180} height={300} alt="Waterheater Index" />
                              </a>
                            </Link>
                          </div>
                          <div className="block-content">
                            <div className="block-title">
                              <Link href={`/catalog/product/${product.id}`}>
                                <a>
                                  {product.attributes.Model}, <span>{product.attributes.Title}</span>
                                </a>
                              </Link>
                            </div>
                            <div className="block-price">
                              {product.attributes.Price} грн
                            </div>
                          </div>
                        </div>
                      </SwiperSlide>
                    ))
                  }
                </Swiper>
              </div>
            </div>
          </div>
        </section>
        <section className="product-benefits">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-12 text-center">
                <h3>
                  {data.ProductBenefits.Title}
                </h3>
                <p dangerouslySetInnerHTML={{__html: data.ProductBenefits.Description}} />
              </div>
              <div className="col-12 col-xl-8">
                <div className="row g-4">
                  {
                    data.ProductBenefits.Benefits.map((benefit, benefitIndex) => (
                      <div className="col-12 col-xl-6" key={benefitIndex}>
                        <div className="benefit-block">
                          <div className="block-icon">
                            <Image src={strapiImage(benefit.Icon.data.attributes.url)} layout="fixed" width={48} height={48} alt="Fire Icon" />
                          </div>
                          <div className="block-content">
                            <div className="block-title">
                              {benefit.Title}
                            </div>
                            <div className="block-description">
                              {benefit.Description}
                            </div>
                          </div>
                        </div>
                      </div>
                    ))
                  }
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="product-slider">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-12 text-center">
                <h3>
                  {data.Slider.Title}
                </h3>
                <p dangerouslySetInnerHTML={{__html: data.Slider.Description}} />
              </div>
            </div>
          </div>
          <div className="container-fluid p-0">
            <div className="col-12">
              <Swiper
                spaceBetween={0}
                slidesPerView={1}
                speed={800}
                className="homepage-slider"
              >
                {
                  data.Slider.Slides.data.map((slide, slideIndex) => (
                    <SwiperSlide key={slideIndex}>
                      <Image src={strapiImage(slide.attributes.url)} layout="fill" objectFit="cover" objectPosition="center" alt="Slider Slide 1"/>
                    </SwiperSlide>
                  ))
                }
              </Swiper>
            </div>
          </div>
        </section>
        <section className="about-company">
          <div className="container">
            <div className="row justify-content-center">
              <div className="col-12 text-center">
                <h3>
                  {data.AboutCompany.Title}
                </h3>
                <p dangerouslySetInnerHTML={{__html: data.AboutCompany.Description}} />
              </div>
              <div className="col-12 col-xl-8">
                <div className="row justify-content-center g-4">
                  {
                    data.AboutCompany.Statistics.map((statistics, statisticsIndex) => (
                      <div className="col-6 col-xl-auto" key={statisticsIndex}>
                        <div className="statistic-block">
                          <div className="block-icon">
                            <Image src={strapiImage(statistics.Icon.data.attributes.url)} layout="fixed" width={48} height={48} alt="Fire Icon" />
                          </div>
                          <div className="block-content">
                            <span>{statistics.Title}</span>
                            {statistics.Description}
                          </div>
                        </div>
                      </div>
                    ))
                  }
                </div>
              </div>
              <div className="col-12 text-center">
                <button className="btn btn-primary">
                  Стати партнером
                </button>
              </div>
            </div>
          </div>
        </section>
        <section className="contacts">
          <div className="container">
            <div className="row gx-xl-5 gy-5">
              <div className="col-12 col-xl-8">
                <div className="frame-block h-100">
                  <div className="row h-100 gy-5">
                    <div className="col-12 col-xl-6">
                      <h3>
                        {data.Contacts.Title}
                      </h3>
                      <div className="row gy-4">
                        {
                          data.Contacts.Contacts.map((contact, contactIndex) => (
                            <div className="col-12" key={contactIndex}>
                              <div className="contact-block">
                                <div className="block-title">
                                  {contact.Label}
                                </div>
                                <div className="block-content">
                                  <div className="block-icon">
                                    <Image src={strapiImage(contact.Icon.data.attributes.url)} layout="fixed" width={18} height={18} alt="Fire Icon" />
                                  </div>
                                  <div className="block-description">
                                    <Link href="#">
                                      {contact.Value}
                                    </Link>
                                  </div>
                                </div>
                              </div>
                            </div>
                          ))
                        }
                      </div>
                    </div>
                    <div className="col-12 col-xl-6 h-100">
                      <div className="map-block">
                        <Image src={Map} alt="Map Image"/>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="col-12 col-xl-4">
                <div className="frame-block">
                  <h3>
                    {data.Form.Title}
                  </h3>
                  <p dangerouslySetInnerHTML={{__html: data.Form.Description}} />
                  <form action="#">
                    <div className="row gy-4">
                      <div className="col-12">
                        <label htmlFor="name" className="form-label required">
                          Ім’я
                        </label>
                        <input type="text" className="form-control" name="name" placeholder="Олександр" required />
                      </div>
                      <div className="col-12">
                        <label htmlFor="phone" className="form-label required">
                          Контактний телефон
                        </label>
                        <input type="text" className="form-control" name="phone" placeholder="+38 (000) 00 00 000" required />
                      </div>
                      <div className="col-12">
                        <label htmlFor="question" className="form-label">
                          Ваше запитання
                        </label>
                        <textarea className="form-control" name="question" placeholder="Опишіть коротко вашу проблему" />
                      </div>
                      <div className="col-12">
                        <button className="btn btn-primary" type="submit">
                          Зворотній виклик
                        </button>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </section>
      </DefaultLayout>
    </>
  )
}

export const getStaticProps = async () => {
  try {
    const data = await fetchContent('homepage', HomepageConfig);

    return {
      props: {
        data,
      },
    };
  } catch (error) {
    console.error(error);
  }

  return {
    props: {},
  };
};