import MosaicFront from '@/images/products/dion-jsd-10-mosaic-front.png';
import MosaicSide from '@/images/products/dion-jsd-10-mosaic-side.png';
import WaterfallFront from '@/images/products/dion-jsd-10-waterfall-front.png';
import WaterfallSide from '@/images/products/dion-jsd-10-waterfall-side.png';
import PoppiesFront from '@/images/products/dion-jsd-10-poppies-front.png';
import PoppiesSide from '@/images/products/dion-jsd-10-poppies-side.png';
import SunflowerFront from '@/images/products/dion-jsd-10-sunflower-front.png';
import SunflowerSide from '@/images/products/dion-jsd-10-sunflower-side.png';
import LilyFront from '@/images/products/dion-jsd-10-lily-front.png';
import LilySide from '@/images/products/dion-jsd-10-lily-side.png';
import PremiumFront from '@/images/products/dion-jsd-10-premium-front.png';
import PremiumSide from '@/images/products/dion-jsd-10-premium-side.png';
import PremiumBlackFront from '@/images/products/dion-jsd-10-premium-black-front.png';
import PremiumBlackSide from '@/images/products/dion-jsd-10-premium-black-side.png';
import PremiumSliverFront from '@/images/products/dion-jsd-10-premium-sliver-front.png';
import PremiumSliverSide from '@/images/products/dion-jsd-10-premium-sliver-side.png';
import ComfortFront from '@/images/products/dion-jsd-10-comfort-black-front.png';
import ComfortSide from '@/images/products/dion-jsd-10-comfort-black-side.png';
import LuxSide from '@/images/products/dion-jsd-11-lux.png';
import TurboFront from '@/images/products/dion-jsd-10-turbo-front.png';
import TurboSide from '@/images/products/dion-jsd-10-turbo-side.png';
import HalfTurboFront from '@/images/products/dion-jsd-10-halfturbo-front.png';
import HalfTurboSide from '@/images/products/dion-jsd-10-halfturbo-side.png';
import GrillFront from '@/images/products/dion-jsd-10-grill-front.png';
import GrillSide from '@/images/products/dion-jsd-10-grill-side.png';
import MountainsFront from '@/images/products/dion-jsd-10-mountains-front.png';
import MountainsSide from '@/images/products/dion-jsd-10-mountains-side.png';
import HalfTurboWithModulatorSide from '@/images/products/dion-jsd-10-half-turbo-with-modulator.png';


export const ProductsList = [
  {
    Category: 'З фото-панеллю',
    Title: 'Мозаїка',
    Model: 'Dion JSD-10',
    Description: 'Dion JSD-10, Мозаїка – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Price: 4900,
    Slug: 'dion-jsd-10-mosaic',
    Images: [MosaicSide, MosaicFront],
    Featured: true,
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Водоспад',
    Description: 'Dion JSD-10, Водоспад – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-waterfall',
    Images: [WaterfallSide, WaterfallFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Маки',
    Description: 'Dion JSD-10, Маки – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-poppies',
    Images: [PoppiesSide, PoppiesFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Соняшник',
    Description: 'Dion JSD-10, Соняшник – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-sunflower',
    Images: [SunflowerSide, SunflowerFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Лілія',
    Description: 'Dion JSD-10, Лілія – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-lily',
    Images: [LilySide, LilyFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Description: 'Dion JSD-10, Преміум – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4800,
    Slug: 'dion-jsd-10-premium',
    Images: [PremiumSide, PremiumFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '18 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Description: 'Dion JSD-08, Преміум (Чорний) – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-08',
    Price: 4300,
    Slug: 'dion-jsd-08-premium-black',
    Images: [PremiumBlackSide, PremiumBlackFront],
    Featured: true,
    Type: 'Димохідна',
    Volume: '8 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-08', },
      { Title: 'Ном. теплова потужність', Value: '16 кВт', },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '8 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '8 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '1,6 кг' },
    ],
  },
  {
    Category: 'Преміум',
    Title: 'Преміум (Сріблястий)',
    Description: 'Dion JSD-10, Преміум (Сріблястий) – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4800,
    Slug: 'dion-jsd-10-premium-silver',
    Images: [PremiumSliverSide, PremiumSliverFront],
    Type: 'Димохідна',
    Volume: '10 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '18 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Люкс',
    Title: 'Комфорт',
    Description: 'Dion JSD-12, Комфорт – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-12',
    Price: 5400,
    Slug: 'dion-jsd-12-comfort',
    Images: [ComfortSide, ComfortFront],
    Type: 'Димохідна',
    Volume: '12 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-12', },
      { Title: 'Ном. теплова потужність', Value: '22 кВт', },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '12 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2,4 кг' },
    ],
  },
  {
    Category: 'Люкс',
    Title: 'Люкс',
    Description: 'Dion JSD-11, Люкс – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-11',
    Price: 5100,
    Slug: 'dion-jsd-11-lux',
    Images: [LuxSide],
    Featured: true,
    Type: 'Димохідна',
    Volume: '11 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-11', },
      { Title: 'Ном. теплова потужність', Value: '22 кВт', },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '11 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '580x310x230' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '115' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2,4 кг' },
    ],
  },
  {
    Category: 'Турбо',
    Title: 'Турбо',
    Description: 'Dion JSD-10D, Турбо – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10D',
    Price: 7100,
    Slug: 'dion-jsd-10d-turbo',
    Images: [TurboSide, TurboFront],
    Featured: true,
    Type: 'Парапетна (Турбо)',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-10D' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '90, 60' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Турбо',
    Title: 'Напівтурбо (З модулятором вогню)',
    Description: 'Dion JSD-10F, Напівтурбо (З модулятором вогню) – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10F',
    Price: 7100,
    Slug: 'dion-jsd-10f-halfturbo-with-modulator',
    Images: [HalfTurboWithModulatorSide],
    Type: 'Парапетна (Турбо)',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-10F' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '590x340x150' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '60' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Турбо',
    Title: 'Напівтурбо',
    Description: 'Dion JSD-10F, Напівтурбо – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10F',
    Price: 6600,
    Slug: 'dion-jsd-10f-halfturbo',
    Images: [HalfTurboSide, HalfTurboFront],
    Type: 'Парапетна (Турбо)',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-10F' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x150' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '60' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Турбо',
    Title: 'Турбо',
    Description: 'Dion JSD-08D, Турбо – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-08D',
    Price: 6600,
    Slug: 'dion-jsd-08d-turbo',
    Images: [TurboSide, TurboFront],
    Type: 'Парапетна (Турбо)',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-08D' },
      { Title: 'Ном. теплова потужність', Value: '16 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '8 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x150' },
      { Title: 'Вага водонагрівача', Value: '10 кг' },
      { Title: 'Діаметр димохідної труби', Value: '90, 60' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '1,6 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Гриль',
    Description: 'Dion JSD-10, Гриль – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-grill',
    Images: [GrillSide, GrillFront],
    Type: 'Димохідна',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Гори',
    Description: 'Dion JSD-10, Гори – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-mountains',
    Images: [MountainsSide, MountainsFront],
    Type: 'Димохідна',
    Volume: '10 л', Specifications: [
      { Title: 'Модель', Value: 'JSD-10' },
      { Title: 'Ном. теплова потужність', Value: '20 кВт' },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '10 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '550x340x164' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '110' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '2 кг' },
    ],
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Description: 'Dion JSD-06, Преміум – це водонагрівач виконаний у стриманому, навіть простому дизайні. Проте стане хорошим рішенням для тих, хто любить лаконічність. Водонагрівач оснащений всіма необхідними системами безпеки, зручний в експлуатації.',
    Model: 'Dion JSD-06',
    Price: 3800,
    Slug: 'dion-jsd-06-premium',
    Images: [PremiumSide, PremiumFront],
    Type: 'Димохідна',
    Volume: '6 л',
    Specifications: [
      { Title: 'Модель', Value: 'JSD-10', },
      { Title: 'Ном. теплова потужність', Value: '9 кВт', },
      { Title: 'Вихід гарячої води (ΔT=25°C)', Value: '6 л./хв.' },
      { Title: 'Коефіцієнт корисної дії', Value: '≥ 84%' },
      { Title: 'Габарити', Value: '440x300x130' },
      { Title: 'Вага водонагрівача', Value: '9 кг' },
      { Title: 'Діаметр димохідної труби', Value: '90' },
      { Title: 'Труба підводу води', Value: 'G 1/2"' },
      { Title: 'Труба відводу води', Value: 'G 1/2"' },
      { Title: 'Труба підводу газу', Value: 'G 1/2"' },
      { Title: 'Номінальний тиск', Value: '1300 Па' },
      { Title: 'Тиск води для загорання', Value: '≥ 0,015 МПа' },
      { Title: 'Вага теплообмінника', Value: '1,2 кг' },
    ],
  },
];