const products = [
  {
    Category: 'З фото-панеллю',
    Title: 'Мозаїка',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-mosaic',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Водоспад',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-waterfall',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Маки',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-poppies',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Соняшник',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-sunflower',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Лілія',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-lily',
    Image: '',
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Model: 'Dion JSD-10',
    Price: 4800,
    Slug: 'dion-jsd-10-premium',
    Image: '',
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Model: 'Dion JSD-08',
    Price: 4300,
    Slug: 'dion-jsd-08-premium-black',
    Image: '',
  },
  {
    Category: 'Преміум',
    Title: 'Преміум (Сріблястий)',
    Model: 'Dion JSD-10',
    Price: 4800,
    Slug: 'dion-jsd-10-premium-silver',
    Image: '',
  },
  {
    Category: 'Люкс',
    Title: 'Комфорт',
    Model: 'Dion JSD-12',
    Price: 5200,
    Slug: 'dion-jsd-12-comfort',
    Image: '',
  },
  {
    Category: 'Люкс',
    Title: 'Люкс',
    Model: 'Dion JSD-11',
    Price: 5100,
    Slug: 'dion-jsd-11-lux',
    Image: '',
  },
  {
    Category: 'Турбо',
    Title: 'Турбо',
    Model: 'Dion JSD-10D',
    Price: 7100,
    Slug: 'dion-jsd-10d-turbo',
    Image: '',
  },
  {
    Category: 'Турбо',
    Title: 'Напівтурбо (З модулятором вогню)',
    Model: 'Dion JSD-10F',
    Price: 7100,
    Slug: 'dion-jsd-10f-halfturbo',
    Image: '',
  },
  {
    Category: 'Турбо',
    Title: 'Напівтурбо',
    Model: 'Dion JSD-10F',
    Price: 6600,
    Slug: 'dion-jsd-10f-halfturbo',
    Image: '',
  },
  {
    Category: 'Турбо',
    Title: 'Турбо',
    Model: 'Dion JSD-08D',
    Price: 6600,
    Slug: 'dion-jsd-08d-turbo',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Гриль',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-grill',
    Image: '',
  },
  {
    Category: 'З фото-панеллю',
    Title: 'Гори',
    Model: 'Dion JSD-10',
    Price: 4900,
    Slug: 'dion-jsd-10-mountains',
    Image: '',
  },
  {
    Category: 'Преміум',
    Title: 'Преміум',
    Model: 'Dion JSD-06',
    Price: 3800,
    Slug: 'dion-jsd-06-premium',
    Image: '',
  },
];